# Generated by Django 5.2.16 on 2026-07-16 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('url', models.URLField(blank=True)),
                ('source_date', models.DateField(blank=True, null=True)),
                ('last_verified_at', models.DateField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('unreviewed', 'Unreviewed'), ('verified', 'Verified'), ('stale', 'Stale'), ('rejected', 'Rejected')], default='unreviewed', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='assets.asset')),
            ],
            options={
                'ordering': ('-source_date', 'title'),
            },
        ),
    ]
