# Generated by Django 5.2.16 on 2026-07-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='check_error',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='source',
            name='http_status',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
