# Generated by Django 5.2.16 on 2026-07-24 19:20

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_alter_asset_status_historicalasset_and_more'),
        ('sources', '0002_source_check_error_source_http_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='link_review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='source',
            name='link_review_status',
            field=models.CharField(choices=[('automatic', 'Use automated result'), ('accepted', 'Accepted after manual review'), ('needs-replacement', 'Needs replacement')], default='automatic', max_length=20),
        ),
        migrations.AddField(
            model_name='source',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='HistoricalSource',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('url', models.URLField(blank=True)),
                ('source_date', models.DateField(blank=True, null=True)),
                ('last_verified_at', models.DateField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('unreviewed', 'Unreviewed'), ('verified', 'Verified'), ('stale', 'Stale'), ('rejected', 'Rejected')], default='unreviewed', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('check_error', models.CharField(blank=True, max_length=240)),
                ('link_review_status', models.CharField(choices=[('automatic', 'Use automated result'), ('accepted', 'Accepted after manual review'), ('needs-replacement', 'Needs replacement')], default='automatic', max_length=20)),
                ('link_review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('asset', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='assets.asset')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical source',
                'verbose_name_plural': 'historical sources',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
