# Generated by Django 5.2.16 on 2026-09-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_source_link_review_notes_source_link_review_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsource',
            name='url',
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.URLField(blank=True, max_length=2048),
        ),
    ]
