# Generated by Django 5.2.16 on 2026-07-16 16:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('record_type', models.CharField(choices=[('organization', 'Organization'), ('facility', 'Facility'), ('program', 'Program'), ('infrastructure', 'Infrastructure'), ('operating-environment', 'Operating environment')], max_length=30)),
                ('short_description', models.CharField(max_length=320)),
                ('unmanned_systems_relevance', models.TextField()),
                ('website_url', models.URLField(blank=True)),
                ('contact_text', models.CharField(blank=True, max_length=240)),
                ('address_line', models.CharField(blank=True, max_length=240)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(default='VA', max_length=2)),
                ('postal_code', models.CharField(blank=True, max_length=12)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('location_precision', models.CharField(choices=[('exact', 'Exact'), ('approximate', 'Approximate'), ('locality', 'Locality only'), ('hidden', 'Hidden')], default='approximate', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('needs-review', 'Needs source review'), ('verified', 'Verified'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('partner', 'Partner only'), ('internal', 'Internal')], default='internal', max_length=12)),
                ('last_verified_at', models.DateField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capabilities', models.ManyToManyField(blank=True, related_name='assets', to='catalog.capability')),
                ('missions', models.ManyToManyField(blank=True, related_name='assets', to='catalog.missionarea')),
                ('platform_domains', models.ManyToManyField(blank=True, related_name='assets', to='catalog.platformdomain')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='catalog.region')),
                ('strategic_categories', models.ManyToManyField(blank=True, related_name='assets', to='catalog.strategiccategory')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('operates', 'Operates'), ('located-at', 'Located at'), ('partners-with', 'Partners with'), ('funds', 'Funds'), ('supports', 'Supports'), ('participates-in', 'Participates in')], max_length=24)),
                ('description', models.CharField(blank=True, max_length=320)),
                ('is_public', models.BooleanField(default=True)),
                ('from_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='assets.asset')),
                ('to_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='assets.asset')),
            ],
            options={
                'ordering': ('relationship_type', 'to_asset__name'),
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['status', 'visibility'], name='assets_asse_status_8d74dd_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['record_type', 'region'], name='assets_asse_record__f32c64_idx'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('name', 'city'), name='unique_asset_name_city'),
        ),
        migrations.AddConstraint(
            model_name='relationship',
            constraint=models.UniqueConstraint(fields=('from_asset', 'to_asset', 'relationship_type'), name='unique_asset_relationship'),
        ),
    ]
