# Generated by Django 5.2.16 on 2026-07-17 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ('name',), 'permissions': [('can_verify_asset', 'Can verify asset records'), ('can_publish_asset', 'Can publish or archive asset records'), ('can_export_asset', 'Can export asset records')]},
        ),
    ]
