# Generated by Django 5.2.16 on 2026-07-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_reset_catalog_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='record_type',
            field=models.CharField(choices=[('university', 'University'), ('organization', 'Organization'), ('facility', 'Facility'), ('program', 'Program'), ('infrastructure', 'Infrastructure'), ('operating-environment', 'Operating environment')], max_length=30),
        ),
    ]
