# Generated by Django 5.2.16 on 2026-07-22 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_alter_asset_record_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('correction', 'Correct an existing record'), ('addition', 'Suggest a new asset'), ('general', 'General feedback')], max_length=16)),
                ('subject', models.CharField(max_length=220)),
                ('details', models.TextField(max_length=5000)),
                ('source_url', models.URLField(blank=True)),
                ('submitter_name', models.CharField(max_length=120)),
                ('submitter_organization', models.CharField(blank=True, max_length=180)),
                ('submitter_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('new', 'New'), ('in-review', 'In review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='new', max_length=16)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_submissions', to='assets.asset')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
