# Generated by Django 5.2.16 on 2026-07-24 19:20

from django.db import migrations


def mark_unreviewed_listings_source_backed(apps, schema_editor):
    Asset = apps.get_model("assets", "Asset")
    Asset.objects.filter(status="published", reviewed_at__isnull=True).update(
        status="source-backed", published_at=None
    )
    Asset.objects.filter(status="published", last_verified_at__isnull=True).update(
        status="source-backed", published_at=None
    )


def restore_legacy_publication_status(apps, schema_editor):
    Asset = apps.get_model("assets", "Asset")
    Asset.objects.filter(status="source-backed").update(status="published")


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0007_alter_asset_status_historicalasset_and_more"),
    ]

    operations = [
        migrations.RunPython(
            mark_unreviewed_listings_source_backed,
            reverse_code=restore_legacy_publication_status,
        )
    ]
