# Generated by Django 5.2.16 on 2026-07-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_asset_review_assignee_asset_review_due_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsavedview',
            name='query_string',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='savedview',
            name='query_string',
            field=models.CharField(blank=True, max_length=4000),
        ),
    ]
