# Generated by Django 5.2.16 on 2026-08-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_alter_historicalsavedview_query_string_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='asset',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='asset',
            name='contact_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='overview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='contact_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='overview',
            field=models.TextField(blank=True),
        ),
    ]
