# Generated by Django 5.2.16 on 2026-08-06 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_asset_contact_email_asset_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='activity_last_verified_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='activity_source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='activity_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('pilot', 'Pilot or demonstration'), ('developing', 'In development'), ('planned', 'Planned'), ('historical', 'Historical')], max_length=20),
        ),
        migrations.AddField(
            model_name='asset',
            name='available_acreage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='asset',
            name='current_activity',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='development_last_verified_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='development_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='development_source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='development_status',
            field=models.CharField(blank=True, choices=[('operational', 'Operational'), ('development-ready', 'Development ready'), ('in-development', 'In development'), ('planned', 'Planned')], max_length=24),
        ),
        migrations.AddField(
            model_name='asset',
            name='infrastructure_access',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='owner_operator',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='asset',
            name='partnership_opportunities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='activity_last_verified_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='activity_source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='activity_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('pilot', 'Pilot or demonstration'), ('developing', 'In development'), ('planned', 'Planned'), ('historical', 'Historical')], max_length=20),
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='available_acreage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='current_activity',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='development_last_verified_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='development_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='development_source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='development_status',
            field=models.CharField(blank=True, choices=[('operational', 'Operational'), ('development-ready', 'Development ready'), ('in-development', 'In development'), ('planned', 'Planned')], max_length=24),
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='infrastructure_access',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='owner_operator',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='partnership_opportunities',
            field=models.TextField(blank=True),
        ),
    ]
