# Generated by Django 5.2.16 on 2026-09-06 23:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0013_asset_activity_last_verified_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="test_access",
            field=models.TextField(
                blank=True, verbose_name="Test-site access and operating constraints"
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="test_aircraft",
            field=models.TextField(blank=True, verbose_name="Published aircraft / testing scope"),
        ),
        migrations.AddField(
            model_name="asset",
            name="test_dimensions",
            field=models.TextField(
                blank=True, verbose_name="Published site and launch / recovery dimensions"
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="test_last_verified_at",
            field=models.DateField(
                blank=True, null=True, verbose_name="Test-site source review date"
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="test_runway_length_ft",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Published runway length (ft)",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="test_source_url",
            field=models.URLField(
                blank=True, max_length=1000, verbose_name="Test-site specification source"
            ),
        ),
        migrations.AddField(
            model_name="historicalasset",
            name="test_access",
            field=models.TextField(
                blank=True, verbose_name="Test-site access and operating constraints"
            ),
        ),
        migrations.AddField(
            model_name="historicalasset",
            name="test_aircraft",
            field=models.TextField(blank=True, verbose_name="Published aircraft / testing scope"),
        ),
        migrations.AddField(
            model_name="historicalasset",
            name="test_dimensions",
            field=models.TextField(
                blank=True, verbose_name="Published site and launch / recovery dimensions"
            ),
        ),
        migrations.AddField(
            model_name="historicalasset",
            name="test_last_verified_at",
            field=models.DateField(
                blank=True, null=True, verbose_name="Test-site source review date"
            ),
        ),
        migrations.AddField(
            model_name="historicalasset",
            name="test_runway_length_ft",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Published runway length (ft)",
            ),
        ),
        migrations.AddField(
            model_name="historicalasset",
            name="test_source_url",
            field=models.URLField(
                blank=True, max_length=1000, verbose_name="Test-site specification source"
            ),
        ),
    ]
