# Generated by Django 5.2.16 on 2026-09-07 01:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0014_test_site_specifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text="Optional readable name; leaves the catalog identity and existing URL unchanged.",
                max_length=220,
                verbose_name="Public display name",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="location_last_verified_at",
            field=models.DateField(
                blank=True, null=True, verbose_name="Location evidence reviewed"
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="location_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("published", "Published reference coordinates"),
                    ("geocoded", "Address geocoding"),
                    ("locality", "Locality reference only"),
                    ("unmapped", "No single point"),
                ],
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="location_notes",
            field=models.TextField(blank=True, verbose_name="What the mapped location represents"),
        ),
        migrations.AddField(
            model_name="asset",
            name="location_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("headquarters", "Headquarters"),
                    ("manufacturing", "Manufacturing site"),
                    ("research", "Research facility"),
                    ("test-site", "Test site"),
                    ("airport", "Airport reference point"),
                    ("campus", "Campus"),
                    ("office", "Office / coordination"),
                    ("installation", "General installation area"),
                    ("service-area", "Service area / multiple sites"),
                ],
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="location_source_url",
            field=models.URLField(blank=True, max_length=1000, verbose_name="Location evidence"),
        ),
        migrations.AddField(
            model_name="asset",
            name="search_aliases",
            field=models.TextField(
                blank=True,
                help_text="Public acronyms, former names, or identifiers, one per line.",
                verbose_name="Search aliases",
            ),
        ),
        migrations.AddField(
            model_name="historicalasset",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text="Optional readable name; leaves the catalog identity and existing URL unchanged.",
                max_length=220,
                verbose_name="Public display name",
            ),
        ),
        migrations.AddField(
            model_name="historicalasset",
            name="location_last_verified_at",
            field=models.DateField(
                blank=True, null=True, verbose_name="Location evidence reviewed"
            ),
        ),
        migrations.AddField(
            model_name="historicalasset",
            name="location_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("published", "Published reference coordinates"),
                    ("geocoded", "Address geocoding"),
                    ("locality", "Locality reference only"),
                    ("unmapped", "No single point"),
                ],
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="historicalasset",
            name="location_notes",
            field=models.TextField(blank=True, verbose_name="What the mapped location represents"),
        ),
        migrations.AddField(
            model_name="historicalasset",
            name="location_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("headquarters", "Headquarters"),
                    ("manufacturing", "Manufacturing site"),
                    ("research", "Research facility"),
                    ("test-site", "Test site"),
                    ("airport", "Airport reference point"),
                    ("campus", "Campus"),
                    ("office", "Office / coordination"),
                    ("installation", "General installation area"),
                    ("service-area", "Service area / multiple sites"),
                ],
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="historicalasset",
            name="location_source_url",
            field=models.URLField(blank=True, max_length=1000, verbose_name="Location evidence"),
        ),
        migrations.AddField(
            model_name="historicalasset",
            name="search_aliases",
            field=models.TextField(
                blank=True,
                help_text="Public acronyms, former names, or identifiers, one per line.",
                verbose_name="Search aliases",
            ),
        ),
    ]
